[package]
name = "compare-env"
version = "0.5.0"
authors = ["lilydjwg <lilydjwg@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "*", features = ["derive"] }

[profile.release]
lto = true
